// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpfenforcer

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfAuditEvent struct {
	Mode   uint32
	Type   uint32
	MntNs  uint32
	Tgid   uint32
	Ktime  uint64
	EventU struct{ Buffer [4120]uint8 }
}

type bpfBuffer struct{ Value [12288]uint8 }

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	VarmorPathRename     *ebpf.ProgramSpec `ebpf:"varmor_path_rename"`
	VarmorPathRenameTail *ebpf.ProgramSpec `ebpf:"varmor_path_rename_tail"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	FileProgs   *ebpf.MapSpec `ebpf:"file_progs"`
	V_auditRb   *ebpf.MapSpec `ebpf:"v_audit_rb"`
	V_buffer    *ebpf.MapSpec `ebpf:"v_buffer"`
	V_fileOuter *ebpf.MapSpec `ebpf:"v_file_outer"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	InitMntNs *ebpf.VariableSpec `ebpf:"init_mnt_ns"`
	Unused    *ebpf.VariableSpec `ebpf:"unused"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	FileProgs   *ebpf.Map `ebpf:"file_progs"`
	V_auditRb   *ebpf.Map `ebpf:"v_audit_rb"`
	V_buffer    *ebpf.Map `ebpf:"v_buffer"`
	V_fileOuter *ebpf.Map `ebpf:"v_file_outer"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.FileProgs,
		m.V_auditRb,
		m.V_buffer,
		m.V_fileOuter,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	InitMntNs *ebpf.Variable `ebpf:"init_mnt_ns"`
	Unused    *ebpf.Variable `ebpf:"unused"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	VarmorPathRename     *ebpf.Program `ebpf:"varmor_path_rename"`
	VarmorPathRenameTail *ebpf.Program `ebpf:"varmor_path_rename_tail"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.VarmorPathRename,
		p.VarmorPathRenameTail,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
